config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/admin' => 'admin_home#index'
  scope '/admin' do
    resources :events
    resources :posts
    resources :users
  end

  post '/logout' => 'auth#logout'
  get '/login' => 'auth#login'
  get '/auth/google_oauth2/callback' => 'auth#oauth2_callback'
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope { order(starts_at: :asc) }

  validates :name, presence: true
  validates :starts_at, presence: true
  validates :ends_at, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  default_scope { order(created_at: :desc) }

  validates :title, presence: true
  validates :body, presence: true

  def author_name
    user.username rescue 'Nobody'
  end

  def rendered_body
    renderer = Redcarpet::Render::HTML.new(no_styles: true, escape_html: true)
    markdown = Redcarpet::Markdown.new(renderer)
    markdown.render(self.body).html_safe
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  serialize :data_hash

  def self.from_omniauth(access_token)
    data = access_token.info
    return nil unless data['email'].match /\@pittco.org$/
    user = User.where(email: data['email']).first

    unless user
      user = User.create username: data['name'],
                         email: data['email'],
                         data_hash: access_token
    end

    user
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_filter :require_user

  private

  def require_user
    redirect_to '/auth/google_oauth2' unless current_user
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id])
  rescue
    nil
  end

end

app/controllers/admin_home_controller.rb
class AdminHomeController < AdminController

  def index
    @user = current_user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def get_event_name
    @event_name = ENV['EVENT_NAME'] || "Pittco"
  end
  
  before_filter :get_event_name
  
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

  def logout
    reset_session
    redirect_to root_path 
  end

  def login
    redirect_to '/auth/google_oauth2'
  end

  def oauth2_callback
    user = User.from_omniauth request.env["omniauth.auth"] 

    if user
      session[:user_id] = user.id
      redirect_to '/admin'
    else
      render 'no_entry', layout: false 
    end
  end

end 

app/controllers/events_controller.rb
class EventsController < AdminController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
    render 'edit'
  end

  def create
    @event = Event.create event_params 

    if @event.valid?
      redirect_to '/admin/events' 
    else
      flash[:alert] = @event.errors.full_messages
      render 'edit'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update event_params 

    if @event.valid?
      redirect_to '/admin/events' 
    else
      flash[:alert] = @event.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to '/admin/events' 
  end

  private

  def event_params
    params.require(:event).permit(:name, :challonge_id, :starts_at, :ends_at)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
    @events = Event.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def letsencrypt
    render text: ENV['LETSENCRYPT_CHALLENGE']
  end
end

app/controllers/posts_controller.rb
class PostsController < AdminController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    render 'edit'
  end

  def create
    @post = current_user.posts.create post_params

    if @post.valid?
      redirect_to '/admin/posts' 
    else
      flash[:alert] = @post.errors.full_messages
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update post_params 

    if @post.valid?
      redirect_to '/admin/posts' 
    else
      flash[:alert] = @post.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to '/admin/posts' 
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < AdminController

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def format_date(date)
    date.strftime("%A @ %l:%M %p")
  end

  def challonge_url(event)
    "http://challonge.com/tournaments/signup/#{event.challonge_id}"
  end 

  def organization_age
    distance_of_time_in_words(Time.now, Time.local(2003,12,25))
  end


end

app/views/admin_home/index.html.erb
<h2>Hello, <%= @user.username %> (<%= @user.email %>) </h2>

<ul>
  <li><%= link_to 'Logout', '/logout', method: :post %></li>
</ul>

app/views/events/edit.html.erb
<h2>Edit Event</h2>

<%= form_for @event do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :challonge_id, 'Challonge URL Fragment' %>
    <%= link_to "- Create New Tournament in Challonge", "http://challonge.com/tournaments/new" %>
    <%= f.text_field :challonge_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :starts_at %>
    <div class="controls" style="position: relative">
    <%= f.datetime_field :starts_at, class: 'form-control datetime' %>
  </div>

  <div class="form-group">
    <%= f.label :ends_at %>
    <div class="controls" style="position: relative">
    <%= f.datetime_field :ends_at, class: 'form-control datetime' %>
  </div>

  <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/events/index.html.erb
<h2>Events</h2>

<%= link_to 'Create New Event', new_event_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Challonge ID</th>
      <th>Starts At</th>
      <th>Ends At</th>
      <th colspan="2">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.challonge_id %></td>
        <td><%= format_date event.starts_at %></td>
        <td><%= format_date event.ends_at %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure you want to delete this alert?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/_discord.erb
<section id="discord" class="content-section text-center">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h1>
        Join our Discord<br>
        <small>All-in-one voice and text chat for gamers that’s free, secure, and works on both your desktop and phone.</small>
      </h1>

      <h2>
        <a href="https://discord.gg/Pag26K5">Join the Server</a><br>
      </h2>

    </div>
  </div>
</section>

app/views/home/_files.erb
<section id="files" class="content-section text-center">
  <h1>
    Files<br>
    <small>In case you forgot to install something important</small>
  </h1>

  <h2>
    <a href="http://files.pittco.loc">Check out our file server</a><br>
    <small>files.pittco.loc</small>
  </h2>
</section>

app/views/home/_news.erb
<section id="news" class="content-section text-center">
  <div class="container">

    <% @posts.each do |post| %>
      <div class="col-md-8 col-md-offset-2">
        <h1><%= post.title %><br>
          <small>
            <%= format_date post.created_at %> - <%= post.author_name %>
          </small>
        </h1>
        <p><%= post.rendered_body %></p>
      </div>
    <% end %>

  </div>
</section>

app/views/home/_tournaments.erb
<section id="tournaments" class="content-section text-center">
  <h1>Tournaments</h1>

  <% @events.each do |event| %>
    <h2>
      <%= event.name %><br>
      <small><%= format_date event.starts_at %></small>
      <% unless event.challonge_id.blank? %>
        <small><a href="<%= challonge_url(event) %>">Sign up</a></small>
      <% end %>
    </h2>
  <% end %>
</section>

app/views/home/_wifi.erb
<section id="wifi" class="content-section text-center">
  <div class="container">
    <div class="col-md-8 col-md-offset-2">
      <h1>
        Wifi<br>
        <small>SSID: PittCo</small><br>
        <small>Password: pittco123</small>
      </h1>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<%= render partial: 'news' %>
<%= render partial: 'tournaments' %>
<%= render partial: 'wifi' %>
<%= render partial: 'files' %>
<%= render partial: 'discord' %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Intranet Admin</title>

    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body> 
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/admin">Pittco Intranet</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/admin/events">Manage Tournaments</a></li>
            <li><a href="/admin/posts">Manage Posts</a></li>
            <li><a href="/admin/users">View Users</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <% if flash[:alert] %>
        <p class="error-message">
          <%= flash[:alert].join(", ") %> 
        </p>
      <% end %>

      <%= yield %>
    </div>
  
    <%= javascript_include_tag 'admin' %>
    <%= yield :footer %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pittco LAN Intranet</title>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>

    <link href="//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="//fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
            <i class="fa fa-bars"></i>
          </button>

          <a class="navbar-brand page-scroll" href="#page-top">
            <span class="light">Intranet</span>
          </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            <li class="hidden"><a href="#page-top"></a></li>
            <li><a class="page-scroll" href="#news">News</a></li>
            <li><a class="page-scroll" href="#tournaments">Tournaments</a></li>
            <li><a class="page-scroll" href="#wifi">Wifi</a></li>
            <li><a class="page-scroll" href="#files">Files</a></li>
            <li><a class="page-scroll" href="#discord">Discord</a></li>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
      <div class="intro-body">
        <div class="container">
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <h1 class="brand-heading">
                <%= image_tag "pittco_logo_header.png" %>
                <%= @event_name %>
              </h1>
              <a href="#news" class="btn btn-circle page-scroll">
                <i class="fa fa-angle-double-down animated"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </header>

    <%= yield %>

    <!-- Footer -->
    <footer>
      <div class="container text-center">
        <div class="left half social">
        <a href="http://pittco.org/facebook">
          <i class="fa fa-facebook-square social"></i>
        </a>

        <a href="http://pittco.org/twitter">
          <i class="fa fa-twitter-square social"></i>
        </a>

        <a href="https://github.com/pittco">
          <i class="fa fa-github-square social"></i>
        </a>
        </div>

        <div class="right half footer-text">
          Made with <i class="fa fa-heart"></i> in Pittsburgh, PA <br>
          <a href="http://pittco.org">The Pittsburgh LAN Coalition</a> <br>
          <%= organization_age.capitalize %> and still going! <br>
          <a href="http://startbootstrap.com/template-overviews/grayscale/">Built with Grayscale</a>
        </div>
      </div>
    </footer>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %> - Markdown allowed.
    &mdash; 
    <%= link_to "Intro To Markdown", "http://blastzonestudios.com/tutorial/2015/02/18/intro-markdown/", target: "blank" %>
    <%= f.text_area :body, class: 'form-control', rows: '10' %>
  </div>

  <%= f.submit class: 'btn btn-default' %>
<% end %>


<% content_for :footer do %>
  <script type="text/javascript">
  </script>
<% end %>

app/views/posts/index.html.erb
<h2>News Posts</h2>
<%= link_to 'Create News Post', new_post_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Created At</th>
      <th colspan="2">&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.author_name %></td>
        <td><%= format_date post.created_at %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete this alert?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<h2>Users</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Created At</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= format_date user.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>